#!/bin/sh
#
# Startup preparations for ffritz on atom.
#
#	- creating/transferring passwords and users
#	- creating dropbear host keys if required
#	- transferring dropbear host keys from persistent memory
#	- transferring roots .ssh from persistent memory
#	
#
# Executed on arm at startup, and on atom by means of this
# script.
#

mach=`uname -m`

echo ffritz_startup on $mach >> $FFLOG

rundir=/usr/local

FFLOG=/var/tmp/ffritz.log

# Create ffritz user/group on both arm and atom
# Audio group required to allow access to usb devices
#
grep ffritz /etc/passwd >/dev/null || echo ffritz:x:8000:8000:ffritz user:/var/media/ftp/ffritz:/bin/sh >> /etc/passwd
grep ffritz /etc/group >/dev/null  || echo ffritz:x:8000: >> /etc/group
grep usb /etc/group >/dev/null     || echo usb:x:8001:ffritz >> /etc/group

if [ $mach == armv6b ]; then
	## ARM
	#

	## Create dummy shadow entry for ffritz so that it's possible to 
	# assign a login
	#
	grep ffritz /etc/shadow >/dev/null  || echo ffritz:x:1:0:99999:7::: >> /etc/shadow

	## Transfer passwords to x86
	#
	cp /etc/shadow /var/remote/var/tmp/shadow

	## create host keys for atom 
	# Since atom does not have a non-volatile storage, and i dont want to use
	# the ftp directory, store them in nvram on arm and transfer them
	# at boot time
	#
	if [ ! -d /nvram/dropbear_x86 ]; then
	    mkdir /nvram/dropbear_x86 || echo failed to create /nvram/dropbear_x86 >> $FFLOG
	fi
	chmod 700 /nvram/dropbear_x86 || echo failed to create /nvram/dropbear_x86 >> $FFLOG
	
	for key in rsa dss ecdsa; do
		if [ ! -f /nvram/dropbear_x86/dropbear_${key}_host_key ]; then
			echo creating /nvram/dropbear_x86/dropbear_${key}_host_key >> $FFLOG
			dropbearkey -t $key -f /nvram/dropbear_x86/dropbear_${key}_host_key || echo dropbearkey failed >> $FFLOG
		fi
	done
	rm -rf /var/remote/var/tmp/dropbear
	cp -ar /nvram/dropbear_x86 /var/remote/var/tmp/dropbear

	## same for root's .ssh
	#
	if [ ! -d /nvram/root-ssh_x86 ]; then
	    mkdir /nvram/root-ssh_x86 || echo failed to create /nvram/root-ssh_x86 >> $FFLOG
	    chmod 700 /nvram/root-ssh_x86
	fi
	cp -ar /nvram/root-ssh_x86 /var/remote/var/tmp/root-ssh
	chmod 700 /var/remote/var/tmp/root-ssh

	# Call this script on atom to finalize startup
	#
	cp $0 /var/remote/var/tmp/ffprep || echo failed to install /var/remote/var/tmp/ffprep from $0 >> $FFLOG
	chmod +x /var/remote/var/tmp/ffprep

	rpc /var/tmp/ffprep

	exit 0
fi

mkdir -p /var/run/mpd
chown ffritz /var/run/mpd

# Run user mounts
#
if [ -f /var/media/ftp/ffritz/.mtab ]; then
    $rundir/etc/usrmount /var/media/ftp/ffritz/.mtab
fi

# A log rotator
#
nohup $rundir/etc/fflogrotate >/dev/null&

# run dropbear
#
if [ -x $rundir/bin/dropbear -a ! -f /var/media/ftp/.skip_dropbear ]; then
    echo Starting dropbear >> $FFLOG
    $rundir/bin/dropbear 2>/dev/console || echo dropbear startup failed >> $FFLOG
else
    echo dropbear not started >> $FFLOG
fi

# run shairport
#
if [ -x $rundir/etc/run_shairport -a ! -f /var/media/ftp/.skip_shairport ]; then
    echo Starting shairport >> $FFLOG
    $rundir/etc/run_shairport
else
    echo shairport skipped >> $FFLOG
fi

# run mpd
#
if [ -x $rundir/etc/runmpd -a ! -f /var/media/ftp/.skip_mpd ]; then
    echo Starting mpd >> $FFLOG
    $rundir/etc/runmpd
else
    echo mpd not started >> $FFLOG
fi

# and lircd
#
if [ -x $rundir/etc/run_lircd -a ! -f /var/media/ftp/.skip_lircd ]; then
    echo Starting lircd >> $FFLOG
    $rundir/etc/run_lircd
else
    echo lircd not started >> $FFLOG
fi

